### ISSUE TITLE
How do you put this into test mode? 

### ISSUE THREAD

**Issue by amityweb** [craftcms/commerce-stripe#145]
How do you put this into test mode? 

There are no fields for the test keys and no switch for Test or Live mode. Cant see anything in the docs referencing it. 

I created a new gateway using Stripe and entered my test keys, but I get an error when paying. Specific error is this, but I dont know if its because its not in test mode when using my test keys, or something else. I need to test the gateway works with test keys before making real transactions. 
 
```
craft\commerce\errors\PaymentSourceException: Invalid source object: must be a dictionary or a non-empty string. See API docs at https://stripe.com/docs' in /home/flintec/craftcms/vendor/craftcms/commerce/src/services/PaymentSources.php:228
Stack trace:
```

Thanks

**Comment by pdaleramirez** [comment]
@amityweb  Once you installed commerce stripe plugin, There are 2 keys to input to get started they are Publishable API Key and Secret API Key in the gateway settings. 

The way Stripe works is that you go to Stripe dashboard then turn on the Viewing test data and go to Developers -> API Keys to get the Publishable key and Secret key. Test keys are prefixed with pk_test and sk_test. There is no test mode setting because when you input the test keys it will automatically create test transaction in your Stripe sandbox.

**Comment by amityweb** [comment]
Thank you. I am familiar with systems that offer fields for live keys and test keys and then a switch to switch between live and test instead is changing keys all the time. So based on that I also assumed there was some other hidden field telling stripe it’s in test mode but you’re saying it’s not it just checks the keys. 

So the error I have must be unrelated to using test keys in the plugin settings and must be something else I’ll look into. 

Thanks for your help.
