### ISSUE TITLE
Expose Stripe client

### ISSUE THREAD

**Issue by sjelfull** [craftcms/commerce-stripe#38]
I need to do updates to subscriptions in a custom module, but as far as I can see there is no way to access the Stripe client with the correct API key/info set already.

Could you make it easier to work with?

**Comment by andris-sevcenko** [comment]
All Stripe SDK methods related to Stripe resources are static, so there's no client to expose, really.

When instantiating the Stripe gateway, it sets all those properties on the Stripe class, anyway, so that's all you need to do, really. This should work for you:

`$stripeGateway = Commerce::getInstance()->getGateways()->getGatewayByHandle($stripeHandle);
Charge::create($requestData);`

One problem here is that it's impossible to have multiple Stripe gateways operating at the same time as the credentials will overlap. When I get around to fixing that, I'll make it possible to ensure that the credentials you need are set on the Stripe class.
