### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by 23d1** [craftcms/commerce-stripe#63]
I'm getting;

```
Uncaught ReferenceError: $ is not defined
    at initStripe (paymentForm.js?v=1562224690:6)
    at paymentForm.js?v=1562224690:103
```

Which means it needs jquery... Any chance we could get a vanilla version, or worst case have commerce-stripe include jquery if not defined?

**Comment by andris-sevcenko** [comment]
Just cut the 2.0.1.2 release which adds the jquery dependency, as that was the fastest solution at the time.

**Comment by 23d1** [comment]
Gotcha. Ended up building a custom solution. Seems to be working! :)

**Comment by totov** [comment]
This change broke my setup as it now includes jQuery after I've already included it (it then resets some foundation scripts). How can I stop it being included by this plugin or make it always included before my other script files?

**Comment by totov** [comment]
I swapped out my own jQuery script tag with the following, which puts it in the `<head>` tag and marks it as having been included for this plugin's dependency:

`{% do view.registerAssetBundle("yii\\web\\JqueryAsset", 1) %}`

**Comment by 23d1** [comment]
The best would be a vanilla JS solution. I've solved it that way.

**Comment by linehammer** [comment]
There is a non-existent variable referenced somewhere. This variable needs to be declared, or you need to make sure it is available in your current script or scope. Basically $ is an alias of jQuery() so when you try to call/access it before declaring the function, it will endup throwing this [$ is not defined](http://net-informations.com/jq/iq/defined.htm) error . This usually indicates that jQuery is not loaded and JavaScript does not recognize the $. Even with $(document).ready , $ is still going to be undefined because jquery hasn't loaded yet.

**To solve this error:**

Load the jQuery CDN library at the beginning of all your javascript files/scripts which uses $ or jQuery, so that $ can be identified in scripts . 

There can be multiple other reasons for this issue:

- Path to jQuery library you included is not correct
- The jQuery library file is corrupted
- Working offline
- Conflict with Other Libraries
