### ISSUE TITLE
Refunding a transaction using stripe causes error

### ISSUE THREAD

**Issue by lukeholder** [craftcms/commerce-stripe#84]
Refunding a transaction using stripe, after changing the gateway driver to the new payment intents gateway causes error since it is trying to use the new gateway driver for a transaction done with the charge gateway.

**Comment by andris-sevcenko** [comment]
The PI gateway differs from Charge gateway in terms of refunds just in what reference is stored. Since you have to refund a "charge", anyway, the PI gateway looks at the transaction reference (`pi_xxxxxxx`) and fetches the first charge of that payment intent and does the refund on that.

A workable solution would be for the PI gateway to look at the reference and see whether it's a charge (`ch_xxxxxxx`) already, and then just use that charge.

**Comment by lukeholder** [comment]
We added a check for backwards compatibility, and the charge gateway has been deprecated: https://github.com/craftcms/commerce-stripe/blob/develop/src/gateways/PaymentIntents.php#L213-L225
